
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team01-f25-05
owner: ucsb-cs156-f25
repo_name: team01-f25-05
pull_requests: [{"author":{"id":"MDQ6VXNlcjkwNTI5Mzc0","is_bot":false,"login":"bsen1","name":"Brian Sen"},"headRefName":"Brian-HelpRequest-create-controller","number":65,"title":"BS -  Create HelpRequest Controller","url":"https://github.com/ucsb-cs156-f25/team01-f25-05/pull/65"},{"author":{"id":"MDQ6VXNlcjM5NzQ0NzMw","is_bot":false,"login":"kennedynguyen1","name":"Kennedy Nguyen"},"headRefName":"kn/create-articles-db","number":64,"title":"KN - create DB tables for Articles","url":"https://github.com/ucsb-cs156-f25/team01-f25-05/pull/64"},{"author":{"id":"U_kgDOCEli4w","is_bot":false,"login":"Hechenjin","name":""},"headRefName":"HY-AddDelete","number":62,"title":"HY - DELETE for RecommendationRequest","url":"https://github.com/ucsb-cs156-f25/team01-f25-05/pull/62"},{"author":{"id":"U_kgDOCEli4w","is_bot":false,"login":"Hechenjin","name":""},"headRefName":"HY-AddPut","number":61,"title":"HY - Put for RecommendationRequest","url":"https://github.com/ucsb-cs156-f25/team01-f25-05/pull/61"},{"author":{"id":"U_kgDOCEli4w","is_bot":false,"login":"Hechenjin","name":""},"headRefName":"HY-AddGet","number":60,"title":"HY - add GET by ID for RecommendationRequest","url":"https://github.com/ucsb-cs156-f25/team01-f25-05/pull/60"},{"author":{"id":"U_kgDOCEli4w","is_bot":false,"login":"Hechenjin","name":""},"headRefName":"HY-Create-Controller","number":59,"title":"HY - RecommendationRequestController","url":"https://github.com/ucsb-cs156-f25/team01-f25-05/pull/59"},{"author":{"id":"U_kgDOCEli4w","is_bot":false,"login":"Hechenjin","name":""},"headRefName":"HY-Create-database-table-for-RecommendationRequest","number":52,"title":"HY-Create database table for RecommendationRequest","url":"https://github.com/ucsb-cs156-f25/team01-f25-05/pull/52"},{"author":{"id":"MDQ6VXNlcjkwNTI5Mzc0","is_bot":false,"login":"bsen1","name":"Brian Sen"},"headRefName":"Brian-HelpRequest-create-db","number":44,"title":"BS - Create Database for HelpRequest Branch","url":"https://github.com/ucsb-cs156-f25/team01-f25-05/pull/44"}]
