
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team01-f25-05
owner: ucsb-cs156-f25
repo_name: team01-f25-05
pull_requests: [{"author":{"id":"U_kgDODfPQcg","is_bot":false,"login":"monraphael-maker","name":"mr-maker"},"headRefName":"MF-put-for-UCSBOrganization-table","number":49,"title":"MF - PUT methods for UCSBOrganization table","url":"https://github.com/ucsb-cs156-f25/team01-f25-05/pull/49"},{"author":{"id":"U_kgDODfPQcg","is_bot":false,"login":"monraphael-maker","name":"mr-maker"},"headRefName":"MF-create-UCSBOrganization-controller","number":48,"title":"MF - create organization controller, add GET /all and POST methods","url":"https://github.com/ucsb-cs156-f25/team01-f25-05/pull/48"},{"author":{"id":"U_kgDODfPQcg","is_bot":false,"login":"monraphael-maker","name":"mr-maker"},"headRefName":"MF-organization-get-by-id","number":46,"title":"MF - add GET by ID method for UCSBOrganization","url":"https://github.com/ucsb-cs156-f25/team01-f25-05/pull/46"},{"author":{"id":"MDQ6VXNlcjkwNTI5Mzc0","is_bot":false,"login":"bsen1","name":"Brian Sen"},"headRefName":"Brian-HelpRequest-create-db","number":44,"title":"Create Database for HelpRequest Branch","url":"https://github.com/ucsb-cs156-f25/team01-f25-05/pull/44"},{"author":{"id":"U_kgDODfPQcg","is_bot":false,"login":"monraphael-maker","name":"mr-maker"},"headRefName":"MF--UCSBOrganization-create-db","number":43,"title":"MF - Create database tables for UCSBOrganization.","url":"https://github.com/ucsb-cs156-f25/team01-f25-05/pull/43"}]
